server:
  port: 8088
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/u2vd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Ast4HS
    driver-class-name: com.mysql.cj.jdbc.Driver
